######################################################################################################
#                                              metadata                                              #
######################################################################################################
[project]
name = "as1oocnl0leb61sj1yew20lt2"
version = "0.0.0"

requires-python = ">= 3.11"
dependencies = []

authors = [{name = "Jevan Goh", email = "javerngoh@gmail.com"}]

######################################################################################################
#                                                pixi                                                #
######################################################################################################
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64"]

[tool.pixi.target.linux-aarch64.activation]
env = { LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$CONDA_PREFIX/lib" }

# ==================================== defaults ====================================
[tool.pixi.dependencies]

# ==================================== environments ====================================
# ----------------------------- dev -----------------------------
[tool.pixi.environments.dev]
features = ["dev"]
solve-group = "default"

# ==================================== features ====================================
# ----------------------------- dev -----------------------------
[tool.pixi.feature.dev.dependencies]
git = ">=2.54.0,<3"

[tool.pixi.feature.dev.tasks]
insert_package = "python insert_package.py"


